### ISSUE TITLE
Citable DOI

### ISSUE THREAD

**Issue by DSbioimaging** [BIOP/ijp-siftalignmultichannel-ij2#2]
Thank you for releasing this code, please consider releasing it in a citable form (e.g. Zenodo) as it would make writing papers slightly easier.

**Comment by romainGuiet** [comment]
Hi @DSbiomedAU ,

Please cite the original paper as we simply add the feature of multi-channel , to this original [Fiji plugin]((https://github.com/axtimwalde/mpicbg/) 

Lowe, D. G. (2004). Distinctive Image Features from Scale-Invariant Keypoints. International Journal of Computer Vision, 60(2), 91–110.[ doi:10.1023/b:visi.0000029664.99615.94](https://doi.org/10.1023/b:visi.0000029664.99615.94) , https://rdcu.be/c1hFC


We created this DOI to fulfill your request 
Romain Guiet, & Nicolas Chiaruttini. (2022). SIFT Alignment multichannel (Version v0). Zenodo. https://doi.org/10.5281/zenodo.7417341

NOTE : this feature will be part of [version 1.5.0 ](https://github.com/axtimwalde/mpicbg/commit/1521c788dd8f1d2fad93c51458bab2daf5de0f9c)

Best regards,

Romain
